/*
Copyright (c) ILM.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Package gendocs renders the ilmctl command tree to Markdown. It is imported
// only by hack/gen-docs.go and by its own tests, never by cmd/ilmctl, so
// cobra/doc and its Markdown dependencies stay out of the shipped binary.
package gendocs

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"k8s.io/cli-runtime/pkg/genericclioptions"

	"github.com/OmniTrustILM/cli/internal/cli"
	"github.com/OmniTrustILM/cli/internal/config"
	"github.com/OmniTrustILM/cli/internal/render"
	"github.com/OmniTrustILM/cli/internal/rootcmd"
)

// stableCacheDir replaces the $HOME-derived --cache-dir default. The real default
// is computed from the generating machine's home directory, which would make the
// generated pages differ per machine and defeat the drift test.
const stableCacheDir = "$HOME/.kube/cache"

// frontMatter is the site front matter of the combined page. toc_max_heading_level
// caps the site's table of contents at the command names; without it the ~180 H3
// subsections make the page's contents list unusable.
const frontMatter = "---\nsidebar_position: 8\ntoc_max_heading_level: 2\n---\n\n"

// pageIntro is the combined page's H1 and lead paragraph.
const pageIntro = `# Command reference

Every ` + "`ilmctl`" + ` command and flag. This page is generated from the command tree —
do not edit it by hand; run ` + "`make docs`" + ` in the cli repository instead.

`

// autoGenFooter matches the footer the per-command pages carry.
const autoGenFooter = "###### Auto generated by spf13/cobra\n"

// Root builds the full command tree without any cluster wiring. Docs generation
// needs only the command and flag metadata, not a live Factory. The
// machine-dependent --cache-dir default is normalized so output is byte-stable
// on every machine.
func Root() *cobra.Command {
	cf := genericclioptions.NewConfigFlags(true)
	if cf.CacheDir != nil {
		*cf.CacheDir = stableCacheDir
	}
	o := &cli.Options{
		ConfigFlags:  cf,
		ConfigLoader: &config.Loader{},
		Printer:      render.NewPrinter(os.Stdout, os.Stderr),
		In:           os.Stdin,
		Out:          os.Stdout,
		ErrOut:       os.Stderr,
		InvokedAs:    "ilmctl",
	}
	return rootcmd.New(o)
}

// commands returns every available command in the tree, parents before children,
// in cobra's own (sorted) order, so the rendering order is deterministic.
func commands(cmd *cobra.Command) []*cobra.Command {
	out := []*cobra.Command{cmd}
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		out = append(out, commands(c)...)
	}
	return out
}

// fileLink is the link handler for the per-command tree: cobra hands it a target
// file name and it is used as-is.
func fileLink(name string) string { return name }

// anchorLink is the link handler for the combined page. Cobra hands it a target
// file name such as "ilmctl_platform_get.md"; the combined page has that command
// as the heading "## ilmctl platform get", whose generated id is
// "ilmctl-platform-get" in both Docusaurus and GitHub. Both slug algorithms
// lowercase the heading, so the anchor is lowercased too. A command name that
// itself contains an underscore would be ambiguous in cobra's file name and
// break this derivation; TestCombinedAnchorsResolve fails loudly on any anchor
// that does not match a generated heading.
func anchorLink(name string) string {
	return "#" + strings.ToLower(strings.ReplaceAll(strings.TrimSuffix(name, ".md"), "_", "-"))
}

// renderCommand writes one command's Markdown into buf using the given link
// handler. It must NOT be called `render`: this file imports the package
// internal/render, and a package-level func of the same name is a redeclaration
// error, not merely a lint warning.
func renderCommand(cmd *cobra.Command, buf *bytes.Buffer, link func(string) string) error {
	cmd.DisableAutoGenTag = true
	if err := doc.GenMarkdownCustom(cmd, buf, link); err != nil {
		return fmt.Errorf("generate markdown for %s: %w", cmd.CommandPath(), err)
	}
	return nil
}

// Tree renders the whole command tree into dir as one Markdown file per command.
func Tree(dir string) error {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("create docs dir: %w", err)
	}
	for _, cmd := range commands(Root()) {
		var buf bytes.Buffer
		if err := renderCommand(cmd, &buf, fileLink); err != nil {
			return err
		}
		buf.WriteString(autoGenFooter)

		basename := strings.ReplaceAll(cmd.CommandPath(), " ", "_") + ".md"
		filename := filepath.Join(dir, basename)
		if err := os.WriteFile(filename, buf.Bytes(), 0o644); err != nil { //nolint:gosec // committed docs; git tracks them at 100644
			return fmt.Errorf("write %s: %w", filename, err)
		}
	}
	return nil
}

// Combined renders the whole command tree as a single Markdown page.
func Combined() ([]byte, error) {
	var buf bytes.Buffer
	buf.WriteString(frontMatter)
	buf.WriteString(pageIntro)

	for _, cmd := range commands(Root()) {
		if err := renderCommand(cmd, &buf, anchorLink); err != nil {
			return nil, err
		}
	}
	buf.WriteString(autoGenFooter)
	return buf.Bytes(), nil
}
