//go:build tools

/*
Copyright (c) ILM.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestBuildDocTree(t *testing.T) {
	dir := t.TempDir()

	err := buildDocTree(dir)
	require.NoError(t, err)

	// The root command page is always emitted.
	root := filepath.Join(dir, "ilmctl.md")
	require.FileExists(t, root)

	// A representative leaf from each command group must be present, proving the
	// whole tree (P1-P5) was walked, not just the root.
	for _, want := range []string{
		"ilmctl_init.md",
		"ilmctl_status.md",
		"ilmctl_check.md",
		"ilmctl_version.md",
		"ilmctl_platform_get.md",
		"ilmctl_platform_generate.md",
		"ilmctl_connector_status.md",
		"ilmctl_proxy_status.md",
		"ilmctl_diagnostics.md",
		"ilmctl_diagnostics_analyze.md",
		"ilmctl_deps_check.md",
		"ilmctl_completion.md",
	} {
		require.FileExists(t, filepath.Join(dir, want), "expected generated page %s", want)
	}

	// Generated pages carry real content (cobra/doc emits a "## " heading) and the
	// auto-gen footer cobra writes, so we can detect drift.
	body, err := os.ReadFile(root)
	require.NoError(t, err)
	require.Contains(t, string(body), "ilmctl")
	require.Contains(t, string(body), "Auto generated by spf13/cobra")
}
