//go:build tools

/*
Copyright (c) ILM.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Command gen-docs renders the cobra command tree to docs/commands/*.md.
// Run via `make docs`; the build tag keeps it out of the shipped binary.
package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
	"k8s.io/cli-runtime/pkg/genericclioptions"

	"github.com/OmniTrustILM/cli/internal/cli"
	"github.com/OmniTrustILM/cli/internal/config"
	"github.com/OmniTrustILM/cli/internal/render"
	"github.com/OmniTrustILM/cli/internal/rootcmd"
)

// rootForDocs builds the full command tree without any cluster wiring.  Docs
// generation only needs the command/flag metadata, not a live Factory.
func rootForDocs() *cobra.Command {
	o := &cli.Options{
		ConfigFlags:  genericclioptions.NewConfigFlags(true),
		ConfigLoader: &config.Loader{},
		Printer:      render.NewPrinter(os.Stdout, os.Stderr),
		In:           os.Stdin,
		Out:          os.Stdout,
		ErrOut:       os.Stderr,
		InvokedAs:    "ilmctl",
	}
	return rootcmd.New(o)
}

// buildDocTree renders the whole command tree into dir as one Markdown file per
// command.  The auto-gen timestamp is replaced with a static footer so output
// is byte-stable and the generated tree can be committed and diffed for drift.
func buildDocTree(dir string) error {
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return fmt.Errorf("create docs dir: %w", err)
	}
	root := rootForDocs()
	return genTreeStable(root, dir)
}

// genTreeStable walks the command tree and writes one Markdown file per
// available command.  It disables cobra's auto-gen timestamp and appends a
// fixed footer so the output is identical on every run.
func genTreeStable(cmd *cobra.Command, dir string) error {
	for _, c := range cmd.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		if err := genTreeStable(c, dir); err != nil {
			return err
		}
	}

	// Disable the dated footer so we can append a stable one ourselves.
	cmd.DisableAutoGenTag = true

	var buf bytes.Buffer
	if err := doc.GenMarkdownCustom(cmd, &buf, func(name string) string { return name }); err != nil {
		return fmt.Errorf("generate markdown for %s: %w", cmd.CommandPath(), err)
	}

	// Append the static footer that the test asserts is present.
	buf.WriteString("###### Auto generated by spf13/cobra\n")

	basename := strings.ReplaceAll(cmd.CommandPath(), " ", "_") + ".md"
	filename := filepath.Join(dir, basename)
	if err := os.WriteFile(filename, buf.Bytes(), 0o600); err != nil {
		return fmt.Errorf("write %s: %w", filename, err)
	}
	return nil
}

func main() {
	dir := "docs/commands"
	if len(os.Args) > 1 {
		dir = os.Args[1]
	}
	if err := buildDocTree(dir); err != nil {
		fmt.Fprintln(os.Stderr, "gen-docs:", err)
		os.Exit(1)
	}
}
